// OneDrive/Documents/heritage-stonebridge/heritage-stonebridge/src/routes/contact/Contact.svelte
<script>
  import SEO from '../../components/SEO.svelte';

  export let data;

  const { agent, office, contactMethods } = data;
</script>

<SEO
  title="Contact Dr. Jan Duffy - Heritage at Stonebridge Real Estate Expert"
  description="Get in touch with Dr. Jan Duffy, your trusted real estate professional for Heritage at Stonebridge. Call 702-222-1964 for luxury homes in Summerlin, Las Vegas."
  canonical="https://heritagestonebridge.com/contact"
  keywords={['Dr. Jan Duffy', 'Heritage Stonebridge real estate', 'Summerlin homes', 'Las Vegas real estate agent', 'contact real estate professional']}
  openGraph={{
    type: 'website',
    url: 'https://heritagestonebridge.com/contact',
    title: 'Contact Dr. Jan Duffy - Heritage at Stonebridge Expert',
    description: 'Connect with Dr. Jan Duffy for luxury real estate in Heritage at Stonebridge, Summerlin.',
    image: 'https://heritagestonebridge.com/images/agent/jan-duffy-contact.jpg'
  }}
/>

<div class="hero-section text-center">
  <div class="container-max px-4">
    <h1 class="text-5xl font-bold mb-4">
      Contact Dr. Jan Duffy
    </h1>
    <p class="text-xl mb-6">
      Your Trusted Heritage at Stonebridge Real Estate Expert
    </p>
  </div>
</div>

<section class="section-padding">
  <div class="container-content">
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-12">

      <!-- Contact Information -->
      <div class="space-y-8">
        <div class="heritage-card p-8">
          <div class="text-center mb-6">
            <div class="w-32 h-32 bg-heritage-secondary rounded-full mx-auto mb-4 flex items-center justify-center">
              <span class="text-4xl">👩‍💼</span>
            </div>
            <h2 class="heritage-heading text-2xl mb-2">{agent.name}</h2>
            <p class="text-heritage-primary font-semibold">{agent.title}</p>
            <p class="text-sm text-gray-600">{agent.experience} of Experience</p>
          </div>

          <div class="space-y-4">
            <div class="flex items-center space-x-3">
              <span class="text-2xl">📞</span>
              <div>
                <p class="font-semibold">Phone</p>
                <a href="tel:{agent.phone}" class="text-heritage-primary hover:text-heritage-dark">
                  {agent.phone}
                </a>
              </div>
            </div>

            <div class="flex items-center space-x-3">
              <span class="text-2xl">✉️</span>
              <div>
                <p class="font-semibold">Email</p>
                <a href="mailto:{agent.email}" class="text-heritage-primary hover:text-heritage-dark">
                  {agent.email}
                </a>
              </div>
            </div>

            <div class="flex items-center space-x-3">
              <span class="text-2xl">🏢</span>
              <div>
                <p class="font-semibold">Office</p>
                <p class="text-gray-700">{office.address}</p>
              </div>
            </div>
          </div>
        </div>

        <!-- Office Hours -->
        <div class="heritage-card p-6">
          <h3 class="heritage-heading text-xl mb-4">Office Hours</h3>
          <p class="text-gray-700">{office.hours}</p>
        </div>
      </div>

      <!-- Contact Form -->
      <div class="heritage-card p-8">
        <h3 class="heritage-heading text-2xl mb-6">Send a Message</h3>

        <form class="space-y-6">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label for="firstName" class="block text-sm font-medium text-gray-700 mb-2">
                First Name *
              </label>
              <input
                type="text"
                id="firstName"
                name="firstName"
                required
                class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-heritage-primary"
              >
            </div>

            <div>
              <label for="lastName" class="block text-sm font-medium text-gray-700 mb-2">
                Last Name *
              </label>
              <input
                type="text"
                id="lastName"
                name="lastName"
                required
                class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-heritage-primary"
              >
            </div>
          </div>

          <div>
            <label for="email" class="block text-sm font-medium text-gray-700 mb-2">
              Email *
            </label>
            <input
              type="email"
              id="email"
              name="email"
              required
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-heritage-primary"
            >
          </div>

          <div>
            <label for="phone" class="block text-sm font-medium text-gray-700 mb-2">
              Phone
            </label>
            <input
              type="tel"
              id="phone"
              name="phone"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-heritage-primary"
            >
          </div>

          <div>
            <label for="message" class="block text-sm font-medium text-gray-700 mb-2">
              Message *
            </label>
            <textarea
              id="message"
              name="message"
              rows="5"
              required
              placeholder="Tell me about your real estate needs..."
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-heritage-primary"
            ></textarea>
          </div>

          <button
            type="submit"
            class="w-full heritage-button text-lg py-3"
          >
            Send Message to Dr. Jan Duffy
          </button>
        </form>
      </div>
    </div>

    <!-- Specialties Section -->
    <div class="mt-16">
      <h3 class="heritage-heading text-center mb-8">Dr. Jan Duffy's Specialties</h3>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {#each agent.specialties as specialty}
          <div class="heritage-card p-6 text-center">
            <p class="font-semibold text-heritage-primary">{specialty}</p>
          </div>
        {/each}
      </div>
    </div>
  </div>
</section>

<style>
  @import '../../assets/css/tailwind.css';
</style>

// searchforhomesinhenderson.com/src/app/contact/page.tsx
import type { Metadata } from 'next'
import { useId } from 'react'

export const metadata: Metadata = {
  title: 'Contact Henderson Homes - Real Estate Experts in Nevada',
  description:
    'Contact our Henderson real estate team for buying, selling, or property valuation services. Local experts helping you navigate the Nevada housing market.',
  keywords: [
    'contact Henderson realtor',
    'Nevada real estate agent',
    'Henderson home buying',
    'real estate consultation',
  ],
  openGraph: {
    title: 'Contact Henderson Homes - Real Estate Experts',
    description: "Get in touch with Henderson's premier real estate team",
    url: 'https://searchforhomesinhenderson.com/contact',
  },
  alternates: {
    canonical: 'https://searchforhomesinhenderson.com/contact',
  },
}

export default function ContactPage() {
  const firstId = useId()
  const lastId = useId()
  const emailId = useId()
  const phoneId = useId()
  const interestId = useId()
  const messageId = useId()

  return (
    <div className="container mx-auto px-4 py-8">
      <header className="text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
          Contact Henderson Homes
        </h1>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto">
          Ready to find your dream home in Henderson? Our local experts are here
          to guide you through every step of your real estate journey.
        </p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
        {/* Contact Form */}
        <div className="bg-white rounded-lg shadow-lg p-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-6">
            Get Started Today
          </h2>
          <form className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label
                  htmlFor={firstId}
                  className="block text-sm font-medium text-gray-700 mb-2"
                >
                  First Name *
                </label>
                <input
                  id={firstId}
                  name="firstName"
                  type="text"
                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                />
              </div>
              <div>
                <label
                  htmlFor={lastId}
                  className="block text-sm font-medium text-gray-700 mb-2"
                >
                  Last Name *
                </label>
                <input
                  id={lastId}
                  name="lastName"
                  type="text"
                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                />
              </div>
            </div>

            <div>
              <label
                htmlFor={emailId}
                className="block text-sm font-medium text-gray-700 mb-2"
              >
                Email Address *
              </label>
              <input
                id={emailId}
                name="email"
                type="email"
                className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                required
              />
            </div>

            <div>
              <label
                htmlFor={phoneId}
                className="block text-sm font-medium text-gray-700 mb-2"
              >
                Phone Number
              </label>
              <input
                id={phoneId}
                name="phone"
                type="tel"
                className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>

            <div>
              <label
                htmlFor={interestId}
                className="block text-sm font-medium text-gray-700 mb-2"
              >
                I'm Interested In *
              </label>
              <select
                id={interestId}
                name="interest"
                className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                required
              >
                <option value="">Select an option</option>
                <option value="buying">Buying a Home</option>
                <option value="selling">Selling a Home</option>
                <option value="valuation">Home Valuation</option>
                <option value="investing">Investment Properties</option>
                <option value="consultation">Market Consultation</option>
              </select>
            </div>

            <div>
              <label
                htmlFor={messageId}
                className="block text-sm font-medium text-gray-700 mb-2"
              >
                Message
              </label>
              <textarea
                id={messageId}
                name="message"
                rows={4}
                className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="Tell us about your real estate goals..."
              />
            </div>

            <button
              type="submit"
              className="w-full bg-blue-600 text-white py-3 rounded-lg font-semibold hover:bg-blue-700 transition-colors"
            >
              Send Message
            </button>
          </form>
        </div>

        {/* Contact Information */}
        <div className="space-y-8">
          <div className="bg-gray-50 rounded-lg p-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-6">
              Contact Information
            </h2>
            <div className="space-y-4">
              <div className="flex items-center">
                <div className="text-blue-600 mr-4">📞</div>
                <div>
                  <div className="font-semibold text-gray-900">Phone</div>
                  <div className="text-gray-600">(702) 555-HOMES</div>
                </div>
              </div>
              <div className="flex items-center">
                <div className="text-blue-600 mr-4">✉️</div>
                <div>
                  <div className="font-semibold text-gray-900">Email</div>
                  <div className="text-gray-600">info@hendersonhomes.com</div>
                </div>
              </div>
              <div className="flex items-center">
                <div className="text-blue-600 mr-4">📍</div>
                <div>
                  <div className="font-semibold text-gray-900">Office</div>
                  <div className="text-gray-600">
                    123 Green Valley Pkwy
                    <br />
                    Henderson, NV 89052
                  </div>
                </div>
              </div>
              <div className="flex items-center">
                <div className="text-blue-600 mr-4">🕒</div>
                <div>
                  <div className="font-semibold text-gray-900">Hours</div>
                  <div className="text-gray-600">
                    Mon-Fri: 8AM-7PM
                    <br />
                    Sat-Sun: 9AM-5PM
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-blue-50 rounded-lg p-8">
            <h3 className="text-xl font-semibold text-gray-900 mb-4">
              Why Choose Henderson Homes?
            </h3>
            <ul className="space-y-2 text-gray-600 text-sm">
              <li>✓ 15+ years of Henderson market expertise</li>
              <li>✓ Top 1% of Nevada real estate agents</li>
              <li>✓ 500+ successful transactions</li>
              <li>✓ Comprehensive market analysis</li>
              <li>✓ Professional photography & marketing</li>
              <li>✓ Negotiation expertise</li>
              <li>✓ Local neighborhood specialists</li>
              <li>✓ Available 7 days a week</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}
